discovery:
  image: postcoder/eureka-service
  ports:
    - "8761:8761"

redis:
  image: redis:alpine
  container_name: redis
  ports: ["6379"]

ukcode:
  image: postcoder/uk-code-service
  ports:
    - "8082:8082"
  links:
    - redis
    
sidecar:
  image: postcoder/sidecar-service
  links:
    - discovery
    - ukcode
  ports:
    - "9999:9999"

eircode:
  image: postcoder/eir-code-service
  ports:
    - "8081:8081"
  links:
    - discovery
    - redis

gateway:
  image: postcoder/edge-service
  ports:
    - "8070:8070"
  links:
    - discovery
    - ukcode
    - sidecar
    - eircode

ui:
  image: postcoder/ui-service
  ports:
    - "80:80"
  links:
    - gateway
