discovery:
  image: postcoder/eureka-service
  ports:
    - "8761:8761"
redis:
  image: redis:alpine
  container_name: redis
  ports: ["6379"]

eircode:
  image: postcoder/eir-code-service
  ports:
    - "8081:8081"
  links:
    - discovery
    - redis

gateway:
  image: postcoder/edge-service
  ports:
    - "8070:8070"
  links:
    - discovery
    - eircode

